version: "3.9"

services:
  qdrant:
    container_name: qdrant-rag
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant-volume:/qdrant/data
    environment:
      - QDRANT_HOST=0.0.0.0
      - QDRANT_PORT=6333
  redis:
    container_name: redis-cache
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  qdrant-volume: